- name: Initialize first control plane
  hosts: morgue-01
  become: true
  tasks:

    - name: Run kubeadm init
      command: >
        kubeadm init
        --apiserver-advertise-address={{ ansible_host }}
        --control-plane-endpoint={{ control_plane_endpoint }}
        --pod-network-cidr={{ pod_network_cidr }}
        
