- name: Run kubeadm init
  command: >
    kubeadm init
    --apiserver-advertise-address={{ ansible_host }}
    --control-plane-endpoint={{ lb_ip }}
    --pod-network-cidr={{ pod_network_cidr }}
    {% if kubeadm_token %} --token {{ kubeadm_token }} {% endif %}
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_output
  notify: Clean join command

- name: Deploy Calico manifeset
  template:
    src: calico.yaml.j2
    dest: /tmp/calico.yaml

- name: Apply Calico
  shell: kubectl apply -f /tmp/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    warn: false

- name: Copy kubeconfig to jumpbox
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/kubeconfig
    flat: yes
