- name: Initialize first control plane
  become: true
  tasks:

    - name: Run kubeadm init
      command: >
        kubeadm init
        --apiserver-advertise-address={{ ansible_host }}
        --control-plane-endpoint={{ control_plane_endpoint }}
        --pod-network-cidr={{ pod_network_cidr }}
        {% if kubeadm_token %} --token {{ kubeadm_token }} {% endif %}
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_output

     - name: Save join command
       set_fact:
         control_plane_join_command: "{{ kubeadm_output.stdout_lines | select('search','kubeadm join') | list | join(' ') }}"

      - name: Copy kubeconfig to jumpbox
        fetch:
          src: /etc/kubernetes/admin.conf
          dest: ~/kubeconfig
          flat: yes
