---
- name: Add Kubernetes apt repository
  hosts: all
  become: true
      
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes signing key
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/{{ kube_version }}/deb/Release.key"
        dest: "/etc/apt/keyrings/kubernetes-apt-keyring.asc"
        mode: '0644'

    - name: Convert key to binary format
      ansible.builtin.command:
        cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.asc"

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kube_version }}/deb/ /"
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

- name: Bootstrap jumpbox
  hosts: jumpbox
  become: true
  tasks:
    
    - name: Install utilities
      apt:
        name:
          - kubectl
          - haproxy
        state: present
        update_cache: true
      
    - name: Add HAProxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart HAProxy

    - name: Ensure HAProxy service is started and enabled
      systemd:
        name: haproxy
        enabled: true
        state: started

- name: Bootstrap Kubernetes controllers
  hosts: control_planes
  become: true

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - kubectl
          - kubeadm
        state: present
        update_cache: yes

- name: Bootstrap Kubernetes workers
  hosts: workers
  become: true

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - socat
          - conntrack
          - ipset
          - kmod
          - kubelet
          - kubectl
          - containerd
        state: present
        update_cache: yes

    - name: Comment out swap in /etc/fstab to disable
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*/swap.img\s+none\s+swap'
        line: '#\g<0>'
        backrefs: yes
        state: present

    - name: Turn swap off immediately
      ansible.builtin.command: swapoff -a
